name: CI - Run Tests and Check

on:
  push:
    branches: [ "*" ]  # Trigger on all branches

permissions:
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Set up Node 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install

      - name: Running Source Formatting
        run: npm run format

      - name: Running Lint
        run: npm run lint

      - name: Running Typecheck
        run: npm run typecheck

      - name: Running Check
        run: npm run check

      - name: Running Build
        run: npm run build

      - name: Running Tests
        run: npm run test

  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: 25

      - name: Install dependencies
        run: |
          ./gradlew clean build

      - name: Running Source Formatting (Spotless)
        run: ./gradlew spotlessApply

      - name: Running Check
        run: ./gradlew check

      - name: Running Tests
        run: ./gradlew test

      - name: Running Integration Tests
        run: ./gradlew testIntegration

      - name: Generating Documentation
        run: ./gradlew generateDocumentation
